
openapi: 3.1.0
info:
  title: Fornecedores API
  version: 1.0.0
  description: Endpoints relacionados ao cadastro e gestão de fornecedores.
tags:
  - name: Fornecedores
paths:
  /fornecedor/create:
    post:
      tags: [Fornecedores]
      summary: Cria um novo fornecedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome_fantasia: { type: string }
                razao_social: { type: string }
                cnpj: { type: string }
                email: { type: string }
      responses:
        "200":
          description: Fornecedor criado
  /fornecedor/list:
    get:
      tags: [Fornecedores]
      summary: Lista fornecedores
      responses:
        "200":
          description: Lista de fornecedores
