
paths:
  /produto/create:
    post:
      tags: [Produtos]
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Produto"
      responses:
        "200":
          description: Produto criado
          content:
            application/json:
              example:
                sucesso: true
                id_produto: "uuid-produto"
  /produto/update:
    post:
      tags: [Produtos]
      summary: Atualiza produto existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Produto"
      responses:
        "200":
          description: Produto atualizado
  /produto/list:
    get:
      tags: [Produtos]
      summary: Lista produtos
      parameters:
        - name: id_fornecedor
          in: query
          schema: { type: string }
      responses:
        "200":
          description: Lista de produtos
  /produto/delete:
    post:
      tags: [Produtos]
      summary: Exclui ou inativa produto
      description: >
        Apenas administradores, fornecedores ou clientes WL podem excluir.  
        Se o produto tiver histórico de vendas, será apenas marcado como excluído.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_produto: { type: string }
      responses:
        "200":
          description: Produto excluído/inativado
